import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Layout } from "antd";
import { Content } from "antd/es/layout/layout";
import SideBar from "./domain/shared/components/SideBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout className="h-screen">
          <SideBar/>
          <Content style={{ overflow: "auto" }}>
            {children}
          </Content>
        </Layout>
      </body>
    </html>
  );
}
